### ISSUE TITLE
Debugger branch support

### ISSUE THREAD

**Issue by Ristovski** [roblabla/ghidra-ci#1]
Seeing as Ghidra 9.3 will have the new debugger feature, it would be nice if there was a separate `debugger` branch CI release.

**Comment by roblabla** [comment]
This is complicated to do with the current architecture of the CI (basically, the CI can only track a single branch, otherwise "Check for new commits" step will fail). I could make another repo dedicated to the CI of the debugger branch, but *meh*, I don't personally need it.

If you really need this, feel free to fork this repository. All you really need to do is to add `ref: debugger` in [this checkout stage](https://github.com/roblabla/ghidra-ci/blob/master/.github/workflows/check_new_commits.yml#L16), and you should have your own repository with nightly builds of debugger branch. Assuming there aren't any new dependencies or other fun stuff to fix in the CI.
